# Generated by Django 6.0.5 on 2026-06-13 05:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_promote_mikeangelo_to_developer'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersWorkbookImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file_sha256', models.CharField(max_length=64, unique=True)),
                ('sheet_summaries', models.JSONField(default=dict)),
                ('imported_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'members_workbook_imports',
                'ordering': ['-imported_at', '-id'],
            },
        ),
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='account',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.CreateModel(
            name='MemberDatabaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField(unique=True)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('member_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('glp_id_number', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('initiation_date', models.DateField(blank=True, null=True)),
                ('passing_date', models.DateField(blank=True, null=True)),
                ('raising_date', models.DateField(blank=True, null=True)),
                ('proficiency_date', models.DateField(blank=True, null=True)),
                ('suspension', models.CharField(blank=True, max_length=100)),
                ('restored', models.CharField(blank=True, max_length=100)),
                ('demit', models.CharField(blank=True, max_length=100)),
                ('lml', models.CharField(blank=True, max_length=100)),
                ('dual_plural_honorary_date', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('appendant_bodies', models.JSONField(default=dict)),
                ('blood_type', models.CharField(blank=True, max_length=30)),
                ('widow_or_sister', models.CharField(blank=True, max_length=255)),
                ('widow_or_sister_date_of_birth', models.DateField(blank=True, null=True)),
                ('meeting_attendance', models.JSONField(default=dict)),
                ('monthly_attendance', models.JSONField(default=dict)),
                ('annual_dues', models.JSONField(default=dict)),
                ('raw_cells', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workbook_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='member_records', to='api.membersworkbookimport')),
            ],
            options={
                'db_table': 'dll347_member_database_records',
                'ordering': ['source_row'],
            },
        ),
        migrations.CreateModel(
            name='LodgeVisitorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField(unique=True)),
                ('meeting', models.CharField(blank=True, max_length=255)),
                ('meeting_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('lodge', models.CharField(blank=True, max_length=255)),
                ('raw_cells', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workbook_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lodge_visitor_records', to='api.membersworkbookimport')),
            ],
            options={
                'db_table': 'dll347_lodge_visitor_records',
                'ordering': ['source_row'],
            },
        ),
        migrations.CreateModel(
            name='BallotingCoinRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField(unique=True)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('member_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('proficiency_date', models.DateField(blank=True, null=True)),
                ('meeting_attendance', models.JSONField(default=dict)),
                ('six_meetings_rule', models.IntegerField(blank=True, null=True)),
                ('three_meetings_rule', models.IntegerField(blank=True, null=True)),
                ('wm_coin_75_percent', models.IntegerField(blank=True, null=True)),
                ('raw_cells', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('workbook_import', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balloting_coin_records', to='api.membersworkbookimport')),
            ],
            options={
                'db_table': 'dll347_balloting_coin_records',
                'ordering': ['source_row'],
            },
        ),
        migrations.CreateModel(
            name='MembersWorkbookSheetSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=100)),
                ('table_key', models.CharField(max_length=50)),
                ('dimension', models.CharField(blank=True, max_length=30)),
                ('freeze_panes', models.JSONField(default=dict)),
                ('merged_ranges', models.JSONField(default=list)),
                ('columns', models.JSONField(default=list)),
                ('row_formats', models.JSONField(default=list)),
                ('workbook_import', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sheet_schemas', to='api.membersworkbookimport')),
            ],
            options={
                'db_table': 'members_workbook_sheet_schemas',
                'constraints': [models.UniqueConstraint(fields=('workbook_import', 'sheet_name'), name='unique_members_workbook_sheet_schema')],
            },
        ),
    ]
