# Generated by Django 6.0.5 on 2026-06-13 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_membersworkbookimport_alter_account_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdatabaserecord',
            name='is_test_record',
            field=models.BooleanField(default=False),
        ),
    ]
