# Generated by Django 6.0.5 on 2026-06-16 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_memberdatabaserecord_is_test_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='ballotingcoinrecord',
            name='member_match_notes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ballotingcoinrecord',
            name='member_match_status',
            field=models.CharField(default='unmatched', max_length=30),
        ),
        migrations.AddField(
            model_name='ballotingcoinrecord',
            name='member_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='balloting_coin_records', to='api.memberdatabaserecord'),
        ),
    ]
