# Generated by Django 6.0.5 on 2026-06-16 17:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ballotingcoinrecord_member_match_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LodgeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField(blank=True)),
                ('place', models.CharField(max_length=255)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_lodge_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dll347_lodge_activities',
                'ordering': ['starts_at', 'id'],
                'indexes': [models.Index(fields=['starts_at'], name='lodge_activity_starts_idx'), models.Index(fields=['status', 'is_published'], name='lodge_activity_status_idx')],
            },
        ),
    ]
