# Generated by Django 6.0.5 on 2026-06-16 19:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_lodgeactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberdatabaserecord',
            name='profile_photo',
            field=models.FileField(blank=True, upload_to=api.models.member_profile_photo_upload_path),
        ),
    ]
