# Generated by Django 6.0.5 on 2026-06-17 08:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_memberdatabaserecord_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPositionHeld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date_range', models.CharField(max_length=150)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions_held', to='api.memberdatabaserecord')),
            ],
            options={
                'db_table': 'dll347_member_positions_held',
                'ordering': ['member_record_id', '-start_date', '-end_date', 'title'],
                'indexes': [models.Index(fields=['member_record', 'title'], name='mem_pos_member_title_idx'), models.Index(fields=['start_date', 'end_date'], name='mem_pos_dates_idx')],
            },
        ),
    ]
