# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_lodgedocument_treasurerreportsummary"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="can_manage_activities",
            field=models.BooleanField(default=False),
        ),
    ]
