# Generated by Codex on 2026-06-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_account_can_manage_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="can_edit_members",
            field=models.BooleanField(default=False),
        ),
    ]
