# Generated by Django 6.0.5 on 2026-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_account_can_edit_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lodgedocument',
            name='category',
            field=models.CharField(choices=[('treasurers_report', 'Treasurers Report'), ('minutes_stated_meeting', 'Minutes of the Stated Meeting'), ('minutes_special_meeting', 'Minutes of the Special Meeting'), ('members_data', 'Members Data')], max_length=40),
        ),
    ]
