# Generated by Django 6.0.5 on 2026-06-20 08:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_lodgedocument_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('tool', models.CharField(choices=[('documents', 'Documents'), ('activity', 'Activity'), ('edit_member', 'Edit Member')], max_length=40)),
                ('last_accessed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_known_window', models.CharField(blank=True, max_length=255)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('access_count', models.PositiveIntegerField(default=1)),
                ('first_accessed_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dll347_tool_access_logs',
                'ordering': ['-last_accessed_at', 'email'],
                'indexes': [models.Index(fields=['tool', '-last_accessed_at'], name='tool_access_tool_last_idx'), models.Index(fields=['email'], name='tool_access_email_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'tool'), name='unique_account_tool_access')],
            },
        ),
    ]
