# Generated by Django 6.0.5 on 2026-06-26 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_preidentifiedemail_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='failed_login_attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
