# Generated by Django 6.0.5 on 2026-06-26 08:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('account_locked', 'Account Locked'), ('password_setup', 'Password Setup'), ('password_reset_requested', 'Password Reset Requested'), ('password_reset', 'Password Reset'), ('member_updated', 'Member Updated'), ('document_uploaded', 'Document Uploaded'), ('document_deleted', 'Document Deleted'), ('activity_created', 'Activity Created'), ('activity_deleted', 'Activity Deleted')], max_length=40)),
                ('target_model', models.CharField(blank=True, max_length=100)),
                ('target_id', models.PositiveIntegerField(blank=True, null=True)),
                ('changes', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'dll347_audit_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_actor_created_idx'), models.Index(fields=['action', '-created_at'], name='audit_action_created_idx'), models.Index(fields=['target_model', 'target_id'], name='audit_target_idx')],
            },
        ),
    ]
