# Generated by Django 6.0.5 on 2026-07-13 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_member_default_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='glp_id_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
