# Generated by Django 6.0.5 on 2026-10-02 16:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_personalinformationvisibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedMemberRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_member_id', models.IntegerField(blank=True, null=True)),
                ('source_row', models.PositiveIntegerField(blank=True, null=True)),
                ('archive_reason', models.CharField(default='Petitioner removed or not present in updated workbook', max_length=255)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('section', models.CharField(blank=True, max_length=150)),
                ('member_number', models.CharField(blank=True, max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('glp_id_number', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('initiation_date', models.DateField(blank=True, null=True)),
                ('passing_date', models.DateField(blank=True, null=True)),
                ('raising_date', models.DateField(blank=True, null=True)),
                ('proficiency_date', models.DateField(blank=True, null=True)),
                ('date_presented', models.DateField(blank=True, null=True)),
                ('date_balloted', models.DateField(blank=True, null=True)),
                ('suspension', models.CharField(blank=True, max_length=100)),
                ('restored', models.CharField(blank=True, max_length=100)),
                ('demit', models.CharField(blank=True, max_length=100)),
                ('lml', models.CharField(blank=True, max_length=100)),
                ('dual_plural_honorary_date', models.CharField(blank=True, max_length=150)),
                ('address', models.TextField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('profile_photo', models.CharField(blank=True, max_length=255)),
                ('default_profile_photo', models.CharField(blank=True, max_length=255)),
                ('appendant_bodies', models.JSONField(default=dict)),
                ('blood_type', models.CharField(blank=True, max_length=30)),
                ('widow_or_sister', models.CharField(blank=True, max_length=255)),
                ('widow_or_sister_date_of_birth', models.DateField(blank=True, null=True)),
                ('meeting_attendance', models.JSONField(default=dict)),
                ('monthly_attendance', models.JSONField(default=dict)),
                ('annual_dues', models.JSONField(default=dict)),
                ('raw_cells', models.JSONField(default=dict)),
                ('record_created_at', models.DateTimeField(blank=True, null=True)),
                ('record_updated_at', models.DateTimeField(blank=True, null=True)),
                ('workbook_import', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_member_records', to='api.membersworkbookimport')),
            ],
            options={
                'db_table': 'dll347_archived_member_records',
                'ordering': ['-archived_at', '-id'],
            },
        ),
    ]
