# Generated by Django 6.0.5 on 2026-10-03 02:46

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_archivedmemberrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_account_id', models.IntegerField(blank=True, null=True)),
                ('old_email', models.EmailField(db_index=True, max_length=254)),
                ('new_email', models.EmailField(db_index=True, max_length=254)),
                ('glp_id_number', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(default='member', max_length=20)),
                ('change_source', models.CharField(choices=[('member_edit', 'Member Edit'), ('workbook_import', 'Workbook Import'), ('admin', 'Admin')], default='member_edit', max_length=50)),
                ('archived_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('member_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_accounts', to='api.memberdatabaserecord')),
            ],
            options={
                'db_table': 'dll347_archived_accounts',
                'ordering': ['-archived_at', '-id'],
            },
        ),
    ]
