# Generated by Django 6.0.5 on 2026-10-03 13:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_archivedaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen', models.CharField(max_length=120)),
                ('member_name', models.CharField(blank=True, max_length=255)),
                ('details', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screen log',
                'verbose_name_plural': 'Screen logs',
                'db_table': 'dll347_screen_logs',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['account', '-created_at'], name='screenlog_acc_created_idx'), models.Index(fields=['screen', '-created_at'], name='screenlog_screen_created_idx')],
            },
        ),
    ]
