# Generated by Django 6.0.5 on 2026-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_screenlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivedmemberrecord',
            name='imes',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='memberdatabaserecord',
            name='imes',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
