# Generated by Django 6.0.5 on 2026-10-08 11:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_archivedmemberrecord_imes_memberdatabaserecord_imes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileAlertWebhookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(default='https://discord.com/api/webhooks/1557707556925739120/BScBlWB610o5u1F_lJUazKx7d62pHYpvXsUhGRmptc_uMWSbZ-QcDa_LFT2Fkqtzi2yk', help_text='Discord webhook URL to post alerts to', max_length=500)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable or disable sending webhook notifications')),
                ('watched_name', models.CharField(default='Mike Angelo Franco', help_text='Name pattern used to match profile views and searches', max_length=255)),
                ('watched_member_id', models.PositiveIntegerField(default=588, help_text='Target member/petitioner record ID for Mike Angelo Franco (default: 588)')),
                ('search_keywords', models.CharField(default='mike, mic', help_text='Comma-separated keywords that trigger alert when searched (case-insensitive)', max_length=500)),
                ('cooldown_seconds', models.PositiveIntegerField(default=30, help_text='Cooldown in seconds per user to prevent duplicate spam')),
                ('ignore_self', models.BooleanField(default=True, help_text="Ignore views or searches performed by Mike's own account")),
                ('self_email', models.EmailField(default='mikeangelofranco@outlook.com', help_text="Mike's account email address to exclude when ignore_self is active", max_length=254)),
                ('total_triggers', models.PositiveIntegerField(default=0, editable=False)),
                ('last_triggered_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_triggered_by', models.CharField(blank=True, editable=False, max_length=255)),
                ('last_status_code', models.IntegerField(blank=True, editable=False, null=True)),
                ('last_error', models.TextField(blank=True, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Profile Alert Setup & Status',
                'verbose_name_plural': 'Webhook Profile Alert Setup & Status',
                'db_table': 'dll347_profile_alert_webhook_config',
            },
        ),
        migrations.CreateModel(
            name='ProfileAlertWebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=255)),
                ('actor_email', models.CharField(blank=True, max_length=255)),
                ('trigger_type', models.CharField(max_length=50)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Sent to Discord'), ('FAILED', 'Failed'), ('SKIPPED_SELF', 'Skipped (Self View)'), ('SKIPPED_COOLDOWN', 'Skipped (Cooldown)'), ('DISABLED', 'Skipped (Webhook Disabled)')], default='SUCCESS', max_length=40)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='api.profilealertwebhookconfig')),
            ],
            options={
                'verbose_name': 'Trigger Event Log',
                'verbose_name_plural': 'Trigger Event Logs',
                'db_table': 'dll347_profile_alert_webhook_logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
