from django.urls import path

from .views import (
    create_lodge_activity_view,
    csrf_view,
    current_account_view,
    forgot_password_view,
    healthcheck,
    login_view,
    lodge_document_detail_view,
    lodge_documents_view,
    lodge_activity_detail_view,
    managed_lodge_activities_view,
    member_account_status_view,
    member_activate_login_view,
    member_deactivate_login_view,
    member_detail_profile_view,
    member_edit_profile_view,
    member_full_profile_view,
    member_list_view,
    member_positions_held_view,
    member_profile_photo_edit_view,
    member_profile_photo_view,
    member_summary_view,
    next_lodge_activity_view,
    preidentified_emails_view,
    reset_password_view,
    logout_view,
    secretary_dashboard_summary_view,
    setup_password_view,
    upcoming_lodge_activities_view,
    user_activity_view,
    validate_reset_password_token_view,
    year_activities_view,
)

app_name = "api"

urlpatterns = [
    path("health/", healthcheck, name="healthcheck"),
    path("auth/csrf/", csrf_view, name="csrf"),
    path("auth/forgot-password/", forgot_password_view, name="forgot-password"),
    path("auth/login/", login_view, name="login"),
    path("auth/reset-password/validate/", validate_reset_password_token_view, name="validate-reset-password-token"),
    path("auth/reset-password/", reset_password_view, name="reset-password"),
    path("auth/setup-password/", setup_password_view, name="setup-password"),
    path("auth/logout/", logout_view, name="logout"),
    path("auth/me/", current_account_view, name="current-account"),
    path("activity/", user_activity_view, name="user-activity"),
    path("members/me/profile/", member_full_profile_view, name="member-full-profile"),
    path("members/<int:member_id>/profile/", member_detail_profile_view, name="member-detail-profile"),
    path("members/<int:member_id>/edit/", member_edit_profile_view, name="member-edit-profile"),
    path("members/<int:member_id>/account-status/", member_account_status_view, name="member-account-status"),
    path("members/<int:member_id>/activate-login/", member_activate_login_view, name="member-activate-login"),
    path("members/<int:member_id>/deactivate-login/", member_deactivate_login_view, name="member-deactivate-login"),
    path("members/me/positions-held/", member_positions_held_view, name="member-positions-held"),
    path("members/me/profile-photo/", member_profile_photo_view, name="member-profile-photo"),
    path("members/<int:member_id>/profile-photo/", member_profile_photo_edit_view, name="member-profile-photo-edit"),
    path("members/list/", member_list_view, name="member-list"),
    path("members/summary/", member_summary_view, name="member-summary"),
    path("secretary/dashboard-summary/", secretary_dashboard_summary_view, name="secretary-dashboard-summary"),
    path("documents/", lodge_documents_view, name="lodge-documents"),
    path("documents/<int:document_id>/", lodge_document_detail_view, name="lodge-document-detail"),
    path("lodge-activities/next/", next_lodge_activity_view, name="next-lodge-activity"),
    path("lodge-activities/year/", year_activities_view, name="year-activities"),
    path("lodge-activities/upcoming/", upcoming_lodge_activities_view, name="upcoming-lodge-activities"),
    path("lodge-activities/manage/", managed_lodge_activities_view, name="managed-lodge-activities"),
    path("lodge-activities/<int:activity_id>/", lodge_activity_detail_view, name="lodge-activity-detail"),
    path("lodge-activities/", create_lodge_activity_view, name="create-lodge-activity"),
    path("preidentified-emails/", preidentified_emails_view, name="preidentified-emails"),
]
